#############################################################################
# Generated by PAGE version 4.10
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Bitstream Vera Serif} -size 20 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {DejaVu Sans} -size 10 -weight normal -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 1 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family {DejaVu Sans} -size 0 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font15
vTcl:font:add_font \
    "-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.fra39
    set site_3_0 $base.fra40
    set site_3_0 $base.fra41
    set site_3_0 $base.fra38
    set site_3_0 $base.fra42
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#ffffff} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1000x1000+479+166
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3825 1170
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "mainwindow"
    vTcl:DefineAlias "$top" "mainwindow" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra39 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 90 \
        -highlightcolor black -width 980 
    vTcl:DefineAlias "$top.fra39" "title_frame" vTcl:WidgetProc "mainwindow" 1
    set site_3_0 $top.fra39
    label $site_3_0.lab43 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightcolor black \
        -text {Fault Injection Simulator} 
    vTcl:DefineAlias "$site_3_0.lab43" "title_label" vTcl:WidgetProc "mainwindow" 1
    button $site_3_0.but39 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Open C File} 
    vTcl:DefineAlias "$site_3_0.but39" "open_c_file" vTcl:WidgetProc "mainwindow" 1
    button $site_3_0.but40 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Open XML File} 
    vTcl:DefineAlias "$site_3_0.but40" "open_xml_file" vTcl:WidgetProc "mainwindow" 1
    place $site_3_0.lab43 \
        -in $site_3_0 -x 9 -y 12 -width 425 -relwidth 0 -height 50 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but39 \
        -in $site_3_0 -x 965 -y 35 -width 94 -height 26 -anchor e \
        -bordermode ignore 
    place $site_3_0.but40 \
        -in $site_3_0 -x 740 -y 35 -width 111 -height 26 -anchor w \
        -bordermode ignore 
    frame $top.fra40 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 300 \
        -highlightcolor black -width 485 
    vTcl:DefineAlias "$top.fra40" "xml_frame" vTcl:WidgetProc "mainwindow" 1
    set site_3_0 $top.fra40
    listbox $site_3_0.lis38 \
        -background {#ffffff} -font font18 -foreground {#000000} -height 240 \
        -highlightcolor black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 470 
    .top37.fra40.lis38 configure -font font18
    .top37.fra40.lis38 insert end text
    vTcl:DefineAlias "$site_3_0.lis38" "xml_table" vTcl:WidgetProc "mainwindow" 1
    label $site_3_0.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font12,object) \
        -foreground {#000000} -highlightcolor black -justify left \
        -text {XML Table} 
    vTcl:DefineAlias "$site_3_0.lab39" "xml_title" vTcl:WidgetProc "mainwindow" 1
    label $site_3_0.lab43 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -highlightcolor black -justify left \
        -text {Breakpoint             Loop              Register            Mask} 
    vTcl:DefineAlias "$site_3_0.lab43" "attributes" vTcl:WidgetProc "mainwindow" 1
    place $site_3_0.lis38 \
        -in $site_3_0 -x 10 -y 51 -width 470 -relwidth 0 -height 240 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab39 \
        -in $site_3_0 -x 10 -y 9 -width 87 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab43 \
        -in $site_3_0 -x 10 -y 33 -width 439 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra41 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 550 \
        -highlightcolor black -width 990 
    vTcl:DefineAlias "$top.fra41" "gdb_frame" vTcl:WidgetProc "mainwindow" 1
    set site_3_0 $top.fra41
    listbox $site_3_0.lis40 \
        -background white -font TkFixedFont -foreground {#000000} -height 510 \
        -highlightcolor black -selectbackground {#c4c4c4} \
        -selectforeground black -width 970 
    .top37.fra41.lis40 configure -font TkFixedFont
    .top37.fra41.lis40 insert end text
    vTcl:DefineAlias "$site_3_0.lis40" "gdb_table" vTcl:WidgetProc "mainwindow" 1
    label $site_3_0.lab41 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font15,object) \
        -foreground {#000000} -highlightcolor black -justify left \
        -text {GDB Output} 
    vTcl:DefineAlias "$site_3_0.lab41" "gdb_output" vTcl:WidgetProc "mainwindow" 1
    place $site_3_0.lis40 \
        -in $site_3_0 -x 10 -y 30 -width 970 -relwidth 0 -height 510 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab41 \
        -in $site_3_0 -x 10 -y 20 -width 226 -relwidth 0 -height 18 \
        -relheight 0 -anchor w -bordermode ignore 
    frame $top.fra38 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 300 \
        -highlightcolor black -width 485 
    vTcl:DefineAlias "$top.fra38" "register_frame" vTcl:WidgetProc "mainwindow" 1
    set site_3_0 $top.fra38
    label $site_3_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font12,object) \
        -foreground {#000000} -highlightcolor black -justify left \
        -text Registers 
    vTcl:DefineAlias "$site_3_0.lab44" "reg_title" vTcl:WidgetProc "mainwindow" 1
    listbox $site_3_0.lis45 \
        -background {#ffffff} -font font17 -foreground {#000000} -height 240 \
        -highlightcolor black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 480 
    .top37.fra38.lis45 configure -font font17
    .top37.fra38.lis45 insert end text
    vTcl:DefineAlias "$site_3_0.lis45" "reg_table" vTcl:WidgetProc "mainwindow" 1
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -highlightcolor black \
        -text {Name     Address     Value } 
    vTcl:DefineAlias "$site_3_0.lab45" "Label1" vTcl:WidgetProc "mainwindow" 1
    place $site_3_0.lab44 \
        -in $site_3_0 -x 10 -y 10 -width 78 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis45 \
        -in $site_3_0 -x 10 -y 51 -width 470 -relwidth 0 -height 240 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 10 -y 34 -width 414 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra42 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 40 \
        -highlightcolor black -width 990 
    vTcl:DefineAlias "$top.fra42" "input_frame" vTcl:WidgetProc "mainwindow" 1
    set site_3_0 $top.fra42
    label $site_3_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font9,object) \
        -foreground {#000000} -highlightcolor black -text (gdb) 
    vTcl:DefineAlias "$site_3_0.lab48" "input_title" vTcl:WidgetProc "mainwindow" 1
    entry $site_3_0.ent46 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent46" "input" vTcl:WidgetProc "mainwindow" 1
    button $site_3_0.but47 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Enter 
    vTcl:DefineAlias "$site_3_0.but47" "enter" vTcl:WidgetProc "mainwindow" 1
    place $site_3_0.lab48 \
        -in $site_3_0 -x 14 -y 12 -width 46 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 72 -y 7 -width 836 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 920 -y 10 -width 59 -height 26 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra39 \
        -in $top -x 5 -y 5 -width 990 -relwidth 0 -height 75 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra40 \
        -in $top -x 5 -y 85 -width 492 -relwidth 0 -height 300 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra41 \
        -in $top -x 5 -y 390 -width 990 -relwidth 0 -height 550 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra38 \
        -in $top -x 995 -y 235 -width 492 -relwidth 0 -height 300 \
        -relheight 0 -anchor e -bordermode ignore 
    place $top.fra42 \
        -in $top -x 5 -y 945 -width 990 -relwidth 0 -height 45 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

  set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

